# Copyright © 2015-2018 Collabora Ltd.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

image: debian:buster-slim

stages:
  - build

variables:
  ci_in_docker: "yes"
  ci_local_packages: "yes"
  ci_parallel: "2"
  ci_sudo: "yes"
  ci_distro: "debian"
  ci_suite: "buster"

.debian-build:
  stage: build
  image: "debian:buster-slim"
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/
  before_script:
    - ./tools/ci-install.sh
    - mkdir -p .ccache
    - export CCACHE_BASEDIR="$(pwd)"
    - export CCACHE_DIR="$CCACHE_BASEDIR/.ccache"
    # Debian's ccache package creates symlinks here for all supported
    # compilers
    - export PATH="/usr/lib/ccache:$PATH"
  script:
    - chown -R user .
    - runuser -u user ./tools/ci-build.sh

production:
  extends: .debian-build
  variables:
    ci_variant: "production"

debug:
  extends: .debian-build
  variables:
    ci_variant: "debug"

reduced:
  extends: .debian-build
  when: manual
  variables:
    ci_variant: "reduced"

legacy:
  extends: .debian-build
  when: manual
  variables:
    ci_variant: "legacy"

cmake:
  extends: .debian-build
  variables:
    ci_buildsys: "cmake-dist"

i686-w64-mingw32-debug:
  extends: .debian-build
  variables:
    ci_host: "i686-w64-mingw32"
    ci_variant: "debug"

i686-w64-mingw32-cmake:
  extends: .debian-build
  when: manual
  variables:
    ci_buildsys: "cmake"
    ci_host: "i686-w64-mingw32"

x86_64-w64-mingw32:
  extends: .debian-build
  variables:
    ci_host: "x86_64-w64-mingw32"

x86_64-w64-mingw32-cmake-debug:
  extends: .debian-build
  variables:
    ci_buildsys: "cmake"
    ci_host: "x86_64-w64-mingw32"
    ci_variant: "debug"

stretch:
  extends: .debian-build
  when: manual
  image: "debian:stretch-slim"
  variables:
    ci_suite: "stretch"

xenial:
  extends: .debian-build
  when: manual
  image: "ubuntu:xenial"
  variables:
    ci_distro: "ubuntu"
    ci_suite: "xenial"

# vim:set sw=2 sts=2 et:
